version: '3.9'
services:
  #Mongodb services
  mongo_db:
     container_name: db_contanerMngo
     image: mongo:latest
     restart: always
     #enee njammakku local host nnu dockerillae  mongodB  aayi connect cheyyannekil
     ports:
       - "2717:27017"

     volumes: 
       - mongo_db:/data/db
  
  #node js api service
  api:
    build: .
    ports:
       - "4000:3000"
    
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo_db:27017
      DB_NAME: SfqDBex
      NAME: sfq

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}



      

  